###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mariadb:
        image: 'mariadb:11.0'
        working_dir: /application
        volumes:
            - '.80:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=testroot
            - MYSQL_DATABASE=test
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
        healthcheck:
          test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
          interval: 10s
          retries: 5
          start_period: 30s
          timeout: 10s
        ports:
            - '36003:3306'

    webserver:
        image: 'nginx:alpine'
        depends_on:
            mariadb:
                condition: service_healthy
                restart: true
        working_dir: /guestsApi
        volumes:
            - '.80:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '36000:80'

    php-fpm:
        build: phpdocker/php-fpm
        depends_on:
            mariadb:
                condition: service_healthy
                restart: true
        working_dir: /application
        volumes:
            - '.80:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/cli/conf.d/99-overrides.ini'
